# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FuL3KUEI4_FKmLdOed4KsMpgEvpQsl_9

SEÇÃO 3: Visualização de dados financeiros

Aula 7. Base de dados com 1 ação.

Importação de bibliotecas
"""

#Instalando o YFinance
!pip install yfinance --upgrade --no-cache-dir

#Importando as Bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pandas_datareader.data as wb
import seaborn as sns
import plotly.express as px

#Importando o YFinance e sobrescrevendo os métodos do pandas_datareader
import yfinance as yf
yf.pdr_override()

#importando dados do Yahoo e colocando em um dataframe
tickers = ['GOLL4.SA']
df_tickers = pd.DataFrame()

for t in tickers:
  df_tickers[t] = wb.DataReader(t, data_source='yahoo', start='2015-1-1')['Adj Close']

df_tickers

"""Aula 8. Base de dados com 2 ações."""

df_tickers.info()

df_tickers.head(5)

df_tickers.tail(5)

df_tickers.describe()

df_tickers[df_tickers['GOLL4.SA'] >= 43.79]

df_tickers[(df_tickers['GOLL4.SA'] >= 1.15) & (df_tickers['GOLL4.SA'] <= 1.16)]

df_tickers.to_csv('gol.csv')

gol_df2 = pd.read_csv('/content/gol.csv')
gol_df2

"""Aula 9. Base de dados com mais ação."""

#importando dados do Yahoo e colocando em um dataframe
tickers = ['GOLL4.SA','CVCB3.SA', 'WEGE3.SA', 'MGLU3.SA', 'TOTS3.SA', 'BOVA11.SA']
acoes_df = pd.DataFrame()

for t in tickers:
  acoes_df[t] = wb.DataReader(t, data_source='yahoo', start='2012-1-1')['Adj Close']

acoes_df

acoes_df = acoes_df.rename(columns={'GOLL4.SA':'GOL', 'CVCB3.SA':'CVC', 'WEGE3.SA':'WEGE', 'MGLU3.SA':'MGLU', 'TOTS3.SA':'TOTS', 'BOVA11.SA':'BOVA11',})

acoes_df

acoes_df.isnull()

acoes_df.isnull().sum()

acoes_df.shape

acoes_df.dropna(inplace=True)

acoes_df.shape

acoes_df.isnull().sum()

acoes_df.to_csv('acoes.csv')

acoes_df = pd.read_csv('/content/acoes.csv')

acoes_df

acoes_df.columns[1:]

acoes_df.describe()

"""Visualização de gráficos

Aula 10. Histograma.
"""

sns.histplot(acoes_df['GOL'], bins=5)

sns.histplot(acoes_df['GOL'], bins=10)

plt.figure(figsize=(10,50))
i = 1
for i in np.arange(1, len(acoes_df.columns)):
  plt.subplot(7, 1, i + 1)
  sns.histplot(acoes_df[acoes_df.columns[i]], kde = True)

sns.histplot(acoes_df['GOL'], bins=10, kde = True)

"""Aula 11. Boxplot."""

sns.boxplot(acoes_df['GOL']);

acoes_df['GOL'].describe()

plt.figure(figsize=(10,50))
i = 1
for i in np.arange(1, len(acoes_df.columns)):
  plt.subplot(7, 1, i + 1)
  sns.boxplot(x = acoes_df[acoes_df.columns[i]])
  plt.title(acoes_df.columns[i])

"""Aula 12. Linhas."""

acoes_df.plot(x = 'Date', figsize = (20, 10), title = 'Histórico das ações');

"""Aula 13. Linhas normalizadas."""

acoes_df_normalizado = pd.DataFrame()
acoes_df_normalizado = acoes_df.copy()
for i in acoes_df_normalizado.columns[1:]:
    acoes_df_normalizado[i] = acoes_df_normalizado [i] / acoes_df_normalizado[i][0]

acoes_df_normalizado

acoes_df_normalizado.plot(x = 'Date', figsize = (20, 10), title = 'Histórico das ações');

"""Aula 14. Gráfico dinâmico."""

figura = px.line(title = 'Histórico do preço das ações')
for i in acoes_df_normalizado.columns[1:]:
  figura.add_scatter(x = acoes_df_normalizado['Date'], y=acoes_df_normalizado[i], name = i)
figura.show()

figura = px.line(title = 'Histórico do preço das ações - normalizado')
for i in acoes_df.columns[1:]:
  figura.add_scatter(x = acoes_df['Date'], y=acoes_df[i], name = i)
figura.show()

"""Aula 15. Exercício.

Olá,

Agora que você aprendeu como realizar algumas análises iniciais e geração de gráficos, o objetivo é gerar outra base de dados com outras empresas de outros setores da economia. Essa nova base será utilizada na maioria dos outros exercícios, pois o objetivo será comparar as métricas financeiras utilizando as duas carteiras de investimentos. Qual será a mais rentável?

Criar uma nova base com as seguintes empresas:

Ambev

Odontoprev

Vivo

Petrobrás

Banco do Brasil

O índice IBOVESPA, assim como para a base de dados anterior

Você também pode escolher outras empresas ao seu critério, pois não vai influenciar na codificação. Na próxima aula você pode assistir o vídeo com a solução

Bom trabalho!
"""

#importando dados do Yahoo e colocando em um segundo dataframe
tickers2 = ['ABEV3.SA', 'ODPV3.SA', 'VIVT3.SA', 'PETR4.SA', '^BVSP']
acoes_ex = pd.DataFrame()

for t in tickers2:
  acoes_ex[t] = wb.DataReader(t, data_source='yahoo', start='2015-1-1')['Adj Close']

acoes_ex

"""Aula 16. Solução para o exercício.

Aula 17. Conclusão.
"""

